version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "march-2023"
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "user"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    ports:
      - "5555:5432"
    restart: on-failure

  app:
    build:
      context: .
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    restart: on-failure
    command: sh -c "npm run start:dev"

  web:
    image: nginx:alpine
    ports:
      - "80:80"
      -

  redis:
    image: redis:alpine
    restart: on-failure